export const contacts = [
   {
      id: Date.now(),
      name: "Jain Doe",
      picture: "/avatar/profile.jpg",
      status: "online",
      lastMsg: "Hey How are you",
      time: "12:40",
   },
   {
      id: Date.now(),
      name: "Jain Doe",
      picture: "/avatar/profile.jpg",
      status: "online",
      lastMsg: "Hey How are you",
      time: "12:40",
   },
   {
      id: Date.now(),
      name: "Jain Doe",
      picture: "/avatar/profile.jpg",
      status: "online",
      lastMsg: "Hey How are you",
      time: "12:40",
   },
   {
      id: Date.now(),
      name: "Jain Doe",
      picture: "/avatar/profile.jpg",
      status: "online",
      lastMsg: "Hey How are you",
      time: "12:40",
   },
   {
      id: Date.now(),
      name: "Jain Doe",
      picture: "/avatar/profile.jpg",
      status: "online",
      lastMsg: "Hey How are you",
      time: "12:40",
   },
   {
      id: Date.now(),
      name: "Jain Doe",
      picture: "/avatar/profile.jpg",
      status: "online",
      lastMsg: "Hey How are you",
      time: "12:40",
   },
   {
      id: Date.now(),
      name: "Jain Doe",
      picture: "/avatar/profile.jpg",
      status: "online",
      lastMsg: "Hey How are you",
      time: "12:40",
   },
]